title: PURPOSE
description: 妄想を地域課題とマッチング
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
baseurl: ""
url: "https://momotaro1105.github.io"
permalink: pretty